# Generated by Django 6.1 on 2026-08-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='bio',
            field=models.TextField(max_length=280),
        ),
    ]
