# Generated by Django 6.1 on 2026-09-01 11:07

import django.core.validators
from django.db import migrations, models


def adicionar_ativo_se_necessario(apps, schema_editor):
    Aluno = apps.get_model('aluno', 'Aluno')
    with schema_editor.connection.cursor() as cursor:
        colunas = {
            coluna.name
            for coluna in schema_editor.connection.introspection.get_table_description(
                cursor, Aluno._meta.db_table
            )
        }
    if 'ativo' not in colunas:
        campo = models.BooleanField(default=True)
        campo.set_attributes_from_name('ativo')
        schema_editor.add_field(Aluno, campo)


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_aluno_campos_obrigatorios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    adicionar_ativo_se_necessario,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='aluno',
                    name='ativo',
                    field=models.BooleanField(default=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='periodo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Informe o CPF no formato 000.000.000-00.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')]),
        ),
    ]
