# Generated by Django 5.2.17 on 2026-09-01 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_alter_aluno_options_aluno_ativo_aluno_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Informe os 11 números do CPF.',
                        regex=r'^(?:\d{11}|\d{3}\.\d{3}\.\d{3}-\d{2})$',
                    )
                ],
            ),
        ),
    ]
